name: xcodeproj_plus
description: A library for reading and modifying XCode projects.
version: 0.3.0
homepage: https://https://open-ci.io/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  petitparser: ^6.0.2
  xml: ^6.5.0
  snapshot: ^0.2.0
  crypto: ^3.0.3
  path: ^1.9.0
  quiver: ^3.2.1
  collection: ^1.18.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
